// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcpbvwntzmqnsojkrdho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcGJ2d250em1xbnNvamtyZGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTgzMDUsImV4cCI6MjA2MjE5NDMwNX0.HWeIbxzMDIYPR1S_EdP7esebz7zTbpw2tPjdhUc8D6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);